jwt:
  secret: 984hg493gh0439rthr0429uruj2309yh937gc763fe87t3f89723gfdgwvjhbfgh
  expiration:
    access-token: 15m
    refresh-token: 1d
spring:
  datasource:
    url: jdbc:sqlserver://localhost:1433;databaseName=LogisticsManagementDb;integratedSecurity=true;trustServerCertificate=true
    driverClassName: com.microsoft.sqlserver.jdbc.SQLServerDriver
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    hibernate:
      naming:
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyJpaCompliantImpl
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      ddl-auto: validate